### ISSUE TITLE
how to export a multichannelbuffer to wav or mp3?

### ISSUE THREAD

**Issue by molo32** [ddf/Minim#102]
I have an audio inside a MultiChannelBuffer
How can I export it to wav or mp3, if you can't, do you know any way to achieve it.

**Comment by ddf** [comment]
Minim doesn't support writing out mp3, but you can write out wav files. For an example, see: https://github.com/ddf/Minim/blob/master/examples/Advanced/OfflineRendering/OfflineRendering.pde
