### ISSUE TITLE
audio spectrum yes! audio sound no

### ISSUE THREAD

**Issue by joshbuddha** [ddf/Minim#12]
trying out this example:
http://processing.org/learning/library/forwardfft.html

the spectrum animates within the draw function so i know its reading the mp3....but there is no sound.

here is my setup:
Processing version 1.5.1
OSX 10.7.2
java version "1.6.0_29"
tried Minim 2.0.2 and 2.1.0 beta

**Comment by ddf** [comment]
closing because it is so out of date
