### ISSUE TITLE
Pushing to Clojars

### ISSUE THREAD

**Issue by noncom** [ddf/Minim#20]
Hey, nice to see the work on the library is going on again! ;)

What about pushing the library to Clojars so as to enable the usage in Clojure?

I will try to do that for my projects, but if you maintain that repository, that would be benificial!

https://github.com/ato/clojars-web/wiki/pushing
https://github.com/technomancy/leiningen/wiki/Repeatability

**Comment by ddf** [comment]
I realize it's been a while, but I want to close this issue if possible.

@noncom The official way to instantiate Minim without Processing is by passing it an object with the methods that Minim looks for, which it then finds by using reflection. Is this incompatible with the way Clojure works? Your FileSystemHandler approach is a good one, I think. To see how Processing handles this you can take a look at the source for their createInput method.

**Comment by noncom** [comment]
Oh,l  just noticed this one. Yeah, me too have very much business in life, so not much time, but I have managed to assemble something. I have already opened a new issue, so this one be closed I guess...
