### ISSUE TITLE
minim.getLineIn() in Ubuntu sets java volume to 0

### ISSUE THREAD

**Issue by hamoid** [ddf/Minim#21]
I discovered that calling minim.getLineIn() sets the java volume to 0 (Ubuntu 13.04, Processing 2.0.3, low latency kernel). Any subsequent attempt to play sounds on Processing fail, as the volume stays at 0.

I realized this by trying all the minim examples one by one and keeping PulseAudio Volume Control open, and looking at the Playback tab. Once the volume goes to 0, opening new sketches and running them does not help. The volume stays at 0 and no sound is produced. Using that tool one can manually drag the volume setting back to audible levels.

If it's possible to control that sound volume from code, maybe it would be enough to add a line to all Minim Processing examples to increase the volume at start up, and no further changes to minim or Processing would be required. I tried with setGain() and setVolume() but it did not change the volume displayed in PulseAudio Volume Control.

**Comment by ddf** [comment]
Finally got around to trying this. I'm on Ubuntu 12.04 and using Processing 3.0a5 and I can't reproduce this problem. Does this still happen for you?

**Comment by hamoid** [comment]
No issues also on ArchLinux 64 bit and Processing 3.0a5. The error was
on 32 bit. I wonder if that has something to do. At least for me it's
fixed :)

**Comment by ddf** [comment]
Ok, thanks. I'm on 64-bit linux too.
