### ISSUE TITLE
Error acquiring TargetDataLine

### ISSUE THREAD

**Issue by thornydre** [ddf/Minim#23]
I have downloaded Minim 2.2.0 few days ago, but I had the same problem on the previous beta version.

On the "setInputMixer.pde" example, when I try to change twice or more the audio input, the console return an error :

==== JavaSound Minim Error ====
==== Error acquiring TargetDataLine: line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.

And for my program, I need to change multiple times the input. Why it works the first time I change ? And is there a way to fix it  ?

**Comment by ddf** [comment]
Not, exactly, but related. AudioInput sets an AudioStream on an AudioOut, but the AudioStream wasn't being closed with the AudioInput was.

Fix in: https://github.com/ddf/Minim/commit/74e051dffd2e8fec10acbe8f6a53617044b4c652
