### ISSUE TITLE
minim.loadFileIntoBuffer causes a NegativeArraySizeException for MP3 files.

### ISSUE THREAD

**Issue by PCuret** [ddf/Minim#24]

**Comment by ddf** [comment]
Partial fix in https://github.com/ddf/Minim/commit/428f8344b5d4fd1ff08a096a7895c92282925109

**Comment by ddf** [comment]
More accurate buffer length for mp3 files with https://github.com/ddf/Minim/commit/b8afdc132a8f9b3c85f78129b34d07363efa67cb

However, the mp3 version of the wav file in the example comes in as longer for some reason.
