### ISSUE TITLE
Release lineIns

### ISSUE THREAD

**Issue by noncom** [ddf/Minim#28]
Currently there is no mechanism to release a lineIn. I think it is presumed that it will be destroyed when exiting the app. But with Clojure workflow, when you do not actually ever exit your app even during development, this renders the audio-in capability unusable, since Minim can get the audio line only on the first launch. On subsequent launches the line appears to be busy and Minim gets some unexisting one which is always silent. Thus, a JVM restart is required to recover. However, this is not acceptable for Clojure development workflow.

The methods `AudioInput.close()` and `Minim.stop()` do not do this job. Please add explicit dispose methods.

**Comment by ddf** [comment]
This should be fixed by https://github.com/ddf/Minim/commit/74e051dffd2e8fec10acbe8f6a53617044b4c652

Can you confirm?

**Comment by noncom** [comment]
Sorry, was totally on other tracks for some while! Yes, I tested it on commit b8afdc1 (later than you specify). The fix seems to be working great!
