### ISSUE TITLE
Sampler begin field from Constant

### ISSUE THREAD

**Issue by scottgarner** [ddf/Minim#30]
I am using a `Constant` patched to `begin` on a `Sampler`. If I set the constant in `setup()` and trigger the sample later, everything is fine. However, if I `setConstant()` and immediately call `trigger()` on the sampler, the value change is ignored, but will affect a later trigger.

Is this a bug, or should I be doing something to force the constant to apply? I've noticed the same problem with `attack`.

**Comment by ddf** [comment]
Fixed in https://github.com/ddf/Minim/commit/767c218524ca0c40d9f184069cbae4e96eb22c2f
