### ISSUE TITLE
Maven or gradle for build?

### ISSUE THREAD

**Issue by davidmoten** [ddf/Minim#31]
Any interest in mavenising this project? Would mean that import is easy (import as maven project) into any java ide. Would also remove the need to include jars in the repository (although would still exist in history which is a bit ugly). Another option would be gradle. I could rejig to maven as a pull request if the project owner is interested.

**Comment by ddf** [comment]
Hi, I'm not particularly interested in doing that at this time, but I will keep it in mind.
