### ISSUE TITLE
getLineIn fails to acquire a TargetDataLine if there isn't an available output channel

### ISSUE THREAD

**Issue by ibanner56** [ddf/Minim#35]
We were trying to open up an input channel with a USB microphone plugged in. Whenever we tried to call the mentioned method we would get an error telling us there was an error due to an unsupported format. When we plugged in a set of headphones to the line-out, the error stopped.

**Comment by ibanner56** [comment]
Ah, accidentally submitted this before I could fill out a description. We were trying to open up an input channel with a USB microphone plugged in. Whenever we tried to call the mentioned method we would get an error telling us there was an error due to an unsupported format. When we plugged in a set of headphones to the line-out, the error stopped.

**Comment by ddf** [comment]
Yes, that error doesn't surprise me. AudioInput requires an output channel to work, which is something I should probably fix. In the meantime, you can use getInputStream if you just want to read from an input and do not need it piped to an output.

**Comment by ddf** [comment]
Fixed in https://github.com/ddf/Minim/commit/8a628d83692e27c31b7726864878bb589e557cae
