### ISSUE TITLE
Minim cannot find BufferedAudio?

### ISSUE THREAD

**Issue by hey-krys** [ddf/Minim#47]
I'm trying to get your script to work (http://code.compartmental.net/2008/10/12/howto-manipulate-an-audiosample-in-minim-20/) to manipulate sound, however I am getting the error message: "BufferedAudio.LEFT" does not exist. 

I've been searching google for solutions for hours now but unfortunately cannot find any solutions. I do have the latest version of minim successfully installed. Any tips?

Thanks in advance.
Krys

**Comment by ddf** [comment]
I got rid of the BufferedAudio interface at some point. Those constants are in AudioSample now:

http://code.compartmental.net/minim/audiosample_class_audiosample.html

**Comment by hey-krys** [comment]
thank you!
