### ISSUE TITLE
deprecated Carbon audioComponent

### ISSUE THREAD

**Issue by CandylabS** [ddf/Minim#49]
When I updated system to OSX 10.11. I got this warning in console:
WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by ddf** [comment]
I'm guessing that's coming from the version of Java on your system. None of the code in Minim deals directly with native classes, it all runs thru JavaSound. So if the JavaSound implementation is making use of that component there's not much I can do about it.

What is the exact situation you encountered this in? Processing sketch or pure Java project?

**Comment by wwagner4** [comment]
Open JDK has open issue about this problem. https://bugs.openjdk.java.net/browse/JDK-8137324.

**Comment by ddf** [comment]
Closing since this is JRE related.
