### ISSUE TITLE
setVolume() not available for AudioPlayer

### ISSUE THREAD

**Issue by sunwangshu** [ddf/Minim#52]
processing 3.0.1, Minim 2.2.2

**Comment by sunwangshu** [comment]
does not support mp3 file?

**Comment by ddf** [comment]
Are you on Windows, Mac, Linux? Can you provide the audio file that is failing to provide a volume control? You might also try using setGain instead.

**Comment by sunwangshu** [comment]
Thanks, you can download my test here:
https://www.dropbox.com/s/32ozcfc5q11e4uu/minimPlayer_3.zip?dl=0

When you pressed 'A', 'S', 'D' you will hear three different tones. I tried to add .setVolume() before .play() and then it says "volume is not supported".

**Comment by sunwangshu** [comment]
BTW I was trying to apply this library to Processing 3. AudioPlayer.setGain() seems to have the same problem. Beside these they all worked magically and it is truly a lifesaver for my final. Thanks so much!

**Comment by ddf** [comment]
Just tested this in Processing 3.3.3 on Windows 10. I got the "volume is not supported" message, but using setGain did work. The availability of gain and volume is going to be JRE-dependent, so I can't fix this until I rewrite these controls.
