### ISSUE TITLE
3D Spatial sound positioning?

### ISSUE THREAD

**Issue by noncom** [ddf/Minim#54]
Could there be any documents or examples available on creating a 3D sound environment with Minim? For example, "placing" sound sources in front, left or right or whatever relative to the listener, and updating them accordingly to how the listener moves and rotates in 6 degrees of freedom?

I am aware that this may be a math-intensive task with lots of concepts, like representing the 3D space, but are there probably any works on this for Minim, or some other works which can be adapted to use with Minim?

**Comment by ddf** [comment]
There is no 3D sound support for Minim and I have no plans to add it. I can imagine this being accomplished by writing a 3D Panner UGen, but that would mean researching all the math behind it yourself. You might see if there are any Java bindings for OpenAL.
