### ISSUE TITLE
EnvelopeFollower is processing signal in mono - please include in documentation

### ISSUE THREAD

**Issue by dyfer** [ddf/Minim#55]
Hello,
I was trying to create a (stereo) envelope follower and I spent a lot of time trying to figure out why the amplitude value for both channels is the same... looking in the source code for EnvelopeFollower, I see it's summing the signal on the input.
I'd argue that this is not a desired behavior, although maybe it's the most common use case... either way, I think this should be mentioned in the docs.
Best,
Marcin

**Comment by ddf** [comment]
Duly noted.
