### ISSUE TITLE
Multichannel audio support?

### ISSUE THREAD

**Issue by msp** [ddf/Minim#56]
Hi 

Is this possible? I can't seem to find an example of doing so..

https://forum.processing.org/two/discussion/16611/multichannel-audio#latest

I also noticed this comment "Using setOutputMixer you can also create AudioOutputs that send sound to specific output channels of a soundcard."

http://code.compartmental.net/minim/minim_method_getlineout.html

Cheers

**Comment by ddf** [comment]
It should be, but from your test output it looks like the Audio 8 DJ is not presenting in a useful way. IIRC, my interface has a mixer for each stereo pair. You might be able to get it to work by defining a new audio device in OSX's Audio Midi Setup for each channel of the Audio 8 DJ you want to use. That might get each to show up as a unique mixer. You'd then set the mixer, ask for a mono output, set the next mixer, ask for a mono output, and so forth.

**Comment by msp** [comment]
I did wonder about that.. I'll be going to my studio today where i have access to another sound card so I'll see how that looks. The Java Sound API might make more sense if the device reports as multiple mixers!

**Comment by ddf** [comment]
Did you have any luck with this?

**Comment by msp** [comment]
Hey @ddf - I jumped to Beads in the end. All doc'd here:

https://forum.processing.org/two/discussion/16611/multichannel-audio#latest

Feel free to close this from my persepctive.

**Comment by ddf** [comment]
Ok, thanks!

**Comment by aliallaoui** [comment]
Beads is no longer supported and multi channel is stil not available easily in Minim, maybe this issue should be reopened ?
