### ISSUE TITLE
audioInput.addEffect()

### ISSUE THREAD

**Issue by rmoughan** [ddf/Minim#57]
The addEffect() method of audioInput is deprecated, as is every other method in the AudioEffects class. Is there anyway to add filters or such to the AudioInput class?

**Comment by ddf** [comment]
You can still use addEffect, even though it is deprecated. Deprecated simply means I plan to remove it in a future release.

The non-deprecated way to do what you want would be to use the UGen framework and patch a LiveInput through whatever effects you want and into an AudioOutput. See: http://code.compartmental.net/minim/liveinput_class_liveinput.html
