### ISSUE TITLE
Docs "If you are using Processing you’ve already got Minim!" is incorrect

### ISSUE THREAD

**Issue by chrisjj** [ddf/Minim#59]
http://code.compartmental.net/tools/minim/ (archived http://web.archive.org/web/20161005032027/http://code.compartmental.net/tools/minim/ ) says:

"If you are using Processing you’ve already got Minim!"

yet if I try to do so in Processing 3.2.1, at `import ddf.minim.*;` I get the error message "No Library found for ddf.minim" http://i.imgur.com/5YbUaKg.png

Workaround: Import the Minim library - Execute Sketch | Import library... | Add library... http://i.imgur.com/qH0Or2H.png , click Filter, type Minim http://i.imgur.com/V9z7E9j.png , click Minim http://i.imgur.com/RVL1cUd.png , click Install.

**Comment by chrisjj** [comment]
> However, you should be able to install it using the library manager in Processing 3.0

Yup. That works fine here.  Installs 2.2.2. I'll note the workaround in the report.

**Comment by ddf** [comment]
Online documentation is now updated.

**Comment by chrisjj** [comment]
Verified http://web.archive.org/web/20161021201221/http://code.compartmental.net/tools/minim/ .
