### ISSUE TITLE
Duplicate Library problem

### ISSUE THREAD

**Issue by CQUPTFC** [ddf/Minim#60]
![error](https://cloud.githubusercontent.com/assets/26280983/23732853/8175965c-04b0-11e7-8a04-9a8d894859dc.png)

**Comment by ddf** [comment]
This happens when you have a version of minim in your sketchbook libraries folder in addition to the one included with the version of Processing you are using. You'll need to remove one of those two versions for it to work.

**Comment by CQUPTFC** [comment]
First I dig down to modes/java/libraries and delete the minim folder there inside the directory that contains Processing.exe.
But no matter which one of those two versions was removed,the procedure will occur an error.
![error](https://cloud.githubusercontent.com/assets/26280983/23786418/f03c2c52-05a7-11e7-88de-a042fe302953.png)
What can I do? My procedure is OpenBCI_GUI.

**Comment by ddf** [comment]
That error does not appear to be related to Minim, so I can't help you there.

**Comment by CQUPTFC** [comment]
Well,at any rate,thank you for that.When I download Processing 3.0,the error is solved.
