### ISSUE TITLE
Can I do trim silence with Minim?

### ISSUE THREAD

**Issue by javenosa** [ddf/Minim#64]
I want to trim silence on beginning and end of an audio.
Just with a threshold.

Can I do with Minim?

Thanks
Jave

**Comment by ddf** [comment]
There is not a single method that you could use to do this, but the framework contains what you'd need to write a small program that would do this. It's not my intention to use Issues for providing more complicated examples like this, so I'd recommend asking your question over on the Processing forum: https://forum.processing.org/two/
