### ISSUE TITLE
Direct recording (question)

### ISSUE THREAD

**Issue by wrey75** [ddf/Minim#66]
Hi,
I use the library outside `Processing.org` for my own project WaveCleaner and works very well. But I can't find an answer to a (quite simple) problem.

I try to connect a `UGen` to a `Recordable` in order to save the generated audio but I want to bypass the line out and, unfortunately, the only way I found is `Minim.createRecorder( Recordable source, String fileName )` but I don't need a `Recordable`. I try to use directly the `AudioSystem` class offered by JAVA sound but doesn't seem a good alternative.

The basic idea is to generate a sound using `UGen`s directly to a wave file (or MP3) without playing it. Have I missed a point? Or I need to create a specific `AudioOutput` class?

**Comment by ddf** [comment]
The OfflineRendering example demonstrates this. The easiest way to accomplish it is by using createRecorder and then having a class that implements Recordable that you push audio to in a loop.

https://github.com/ddf/Minim/blob/master/examples/Advanced/OfflineRendering/OfflineRendering.pde

**Comment by wrey75** [comment]
So simple... I just implemented in my code and works like a charm! Thank you very much.
