### ISSUE TITLE
Question re: using with Android

### ISSUE THREAD

**Issue by narner** [ddf/Minim#67]
More a question than anything, but is it possible to use the Minim library on an Android device? I've been trying to run the Minim example projects via Processing for Android, but none seem to run - I'm trying to determine whether this is an issue with running on an Emulator, or something else...wanted to figure that out before I purchase an actual Android device. Thanks!

**Comment by ddf** [comment]
unfortunately not. as far as i understand, JavaSound is not available on Android and Minim relies on JavaSound for most of its functionality.
