### ISSUE TITLE
sample player

### ISSUE THREAD

**Issue by michaeldoherty98** [ddf/Minim#68]
Hi there,
I have been trying to create a keyboard style sampler that plays a user recorded sample at different pitches. I have tried to do this using TickRate but can't seem to get it to work. Any ideas or suggestions?

**Comment by ddf** [comment]
The Sampler UGen will be easier to use for this: http://code.compartmental.net/minim/sampler_class_sampler.html

**Comment by michaeldoherty98** [comment]
How could I use setSampleRate to say, play the sample at a different rate when the 's' or 'd' keys are pressed for example? or should I use something else?

**Comment by ddf** [comment]
setSampleRate is used by the UGen framework to alert UGens of the sample rate of the final audio output. When using Sampler, you should call setLastValue on the rate member of Sampler when a key is pressed and pass in the playback rate you want (eg 0.5 is half speed, 2 is double speed). Then call trigger() on the Sampler.

**Comment by michaeldoherty98** [comment]
Sorry but how would i do that? I'm not very up to speed on all of this yet

**Comment by ddf** [comment]
Then I'd suggest looking through all of the examples to see how the UGens are used. I don't really have the bandwidth to walk you through exactly what you want to do and these Issues are not really the place for it anyway. I'd recommend taking your question to the [Processing forum](https://forum.processing.org/two/) if you need more help.

**Comment by michaeldoherty98** [comment]
Okay thanks, thank you for your help :)
