### ISSUE TITLE
problem with sample.trigger ()

### ISSUE THREAD

**Issue by loboere** [ddf/Minim#74]
When you click, it takes a little time to play the samples
how it reproduces instantaneously when clicking

 ```

import ddf.minim.*;
import ddf.minim.analysis.*;
import ddf.minim.ugens.*;

 
 int buffersize=65536; //32768 //16384 //65536
int samplerate=44100;
 Minim minim;  
AudioOutput mainOut;
MultiChannelBuffer sampleBuffer;
Sampler            sampler;



 void setup()
{
   size(512, 480);
   minim = new Minim(this);//AudioOutput getLineOut(Minim.MONO, int bufferSize) para salida de audio
 
 mainOut = minim.getLineOut(Minim.MONO,buffersize,samplerate);
sampleBuffer     = new MultiChannelBuffer(samplerate,1);
  sampler = new Sampler( sampleBuffer, samplerate, 1 );
}

void draw()
{
  if (mousePressed)
 {
  for(int i=0 ; i<samplerate ; i++ ){
 sampleBuffer.setSample(0,i,random(1));
  }
  
 sampler.setSample(sampleBuffer,samplerate);
sampler.unpatch(mainOut);
sampler.patch(mainOut);
 sampler.trigger (); 
}
}
```
``

**Comment by ddf** [comment]
Your `bufferSize` is very large, which is what causes the delay. With `samplerate=44100` the `AudioOutput` is going to want 44100 samples per second. With `buffersize=65536` you are essentially saying that the `AudioOutput` should a little over a second of audio ready to go at all times, this is called latency. So when you click the mouse and start your sample playing, you won't actually hear it until about 65536 samples (or just over a second) later. If you want to hear the sound "instantly" you need to reduce your `buffersize`. Try 1024 or 512. There will be a lower limit, though, where the program cannot generate samples fast enough for your output, which can cause breaks in the sounds, but that all depends on what kind of audio driver is being used and how much audio processing needs to happen.
