### ISSUE TITLE
Using this in Android

### ISSUE THREAD

**Issue by HBiSoft** [ddf/Minim#80]
As the title says, I'm trying to get this to work for android, but `javax.sound.sampled` is not supported by android. Can I replace it with android's MediaPlayer or is `javax.sound.sampled` required for this library to work?

**Comment by ddf** [comment]
Unfortunately the library has several direct dependencies on JavaSound, so it is not possible to use on Android.

**Comment by HBiSoft** [comment]
@ddf Thanks for the reply. Can you perhaps suggest similar libraries for Android?

**Comment by ddf** [comment]
I haven't really done any Android development, so I'm not sure what's out there.
