### ISSUE TITLE
Drawing into the Wavetable

### ISSUE THREAD

**Issue by luisArandas** [ddf/Minim#86]
Hello and good afternoon!
I am having some problems with an issue I'd like to solve.
I would like to make the wavetable method in Minim drawable like pure data waveform plotting.
Drawing into it with the mousePressed() function. Being able to draw the waveform with the mouse exactly like pure data window.
Any ideas?
Best, Luis

**Comment by ddf** [comment]
This is more a question for the Processing forum, but you can construct an empty Wavetable with `new Wavetable(size)` and then you could write a sketch that maps mouse position to a sample index and value when `mousePressed` is called and use `set` on the Wavetable to fill in the Wavetable data. Providing a drawing an interface is beyond the scope of what Minim is intended for.
